name: sprout_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  rxdart: ^0.27.3
  shared_preferences: ^2.0.7
  intl: ^0.17.0
  pin_code_fields: ^7.4.0
  image_picker: ^0.8.4+9
  flutter_easyloading: ^3.0.3
  shimmer: ^2.0.0
  flutter_screenutil: ^5.5.3+2
  flutter_styled_toast: ^2.1.3
  get_storage: ^2.0.3
  community_material_icon: ^5.9.55
  dropdown_button2: ^1.1.1
  step_progress_indicator: ^1.0.2
  flutter_pw_validator: ^1.5.0
  neon_circular_timer: ^0.0.7
  flutter_svg: ^1.1.6
  iconsax: ^0.0.8
  badges: ^3.0.2
  flutter_masked_text2: ^0.9.1
  nfc_manager: ^3.2.0
  file_picker: ^4.6.1
  fl_chart: ^0.55.2
  get_it: ^7.2.0
  local_auth: ^2.1.5
  form_field_validator: ^1.1.0
  basic_utils: ^5.5.1
  firebase_messaging: ^14.0.3
  firebase_core: ^2.1.1

  lottie: ^1.0.0
  open_file: ^3.0.3
  flutter_spinkit: ^5.1.0
  path_provider: ^2.0.11
  share: ^2.0.4
  url_launcher: ^6.1.6
  clipboard: ^0.1.2+8
  pattern_formatter: ^2.0.0
  get_time_ago: ^1.1.3
  pdf: ^3.8.4
  flutterwave_standard: 1.0.7
  email_validator: ^2.1.17
  # pspdfkit_flutter: ^3.5.1
  
  device_info_plus: ^3.2.4
  open_store: ^0.4.0
  package_info_plus: ^1.4.2
  dartdoc: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/
    - assets/lottie/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
         
    - family: Mont
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
         
    - family: Neue
      fonts:
        - asset: assets/fonts/NeueMontreal-Regular.otf
        - asset: assets/fonts/NeueMontreal-Bold.otf
     
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
